In [3]:
import numpy as np

# a) Define A matrix and b vector
b1=1
b2=2
b3=3
A = np.array([[2, 2, 0],  
              [2, 1, 1],
              [-7, 2, -3]])

b = np.array([b1, b2, b3])
print("The system of linear equations in matrix form is: \n A = [[2, 2, 0],[1, 1, 1],[-7, 2, -3]] \n x = [x1, x2, x3] \n b = [b1, b2, b3]")

# b) Calculate determinant
det_A = np.linalg.det(A)
print("Determinant:", det_A)

# c) Compute inverse
inv_A = np.linalg.inv(A)
print("Inverse:\n", inv_A)

# d) Characteristic equation  
char_eq = np.poly1d([1, -3, -4, 18])

# e) Solve characteristic equation
evals = np.roots(char_eq)
print("Eigenvalues:", evals)

# f) Interpret eigenvalues
print("Eigenvalues represent scaling factors of eigenvectors")

# g) Check positive definiteness
print("A is not positive definite because of negative eigenvalue")

The system of linear equations in matrix form is: 
 A = [[2, 2, 0],[1, 1, 1],[-7, 2, -3]] 
 x = [x1, x2, x3] 
 b = [b1, b2, b3]
Determinant: -12.0
Inverse:
 [[ 0.41666667 -0.5        -0.16666667]
 [ 0.08333333  0.5         0.16666667]
 [-0.91666667  1.5         0.16666667]]
Eigenvalues: [-2.26697461+0.j          2.63348731+1.00241825j  2.63348731-1.00241825j]
Eigenvalues represent scaling factors of eigenvectors
A is not positive definite because of negative eigenvalue


In [4]:
import numpy as np

# Original matrix
A = np.array([[2, 2, 0],  
              [2, 1, 1],
              [-7, 2, -3]])

# a) Matrix equation
print('Matrix Equation:')
print('A * x = b')

# b) Calculate determinant
det = np.linalg.det(A)
print('\nDeterminant of A:') 
print(det)

# c) Calculate inverse
A_inv = np.linalg.inv(A)
print('\nInverse of A:')
print(A_inv)

# d) Characteristic equation
print('\nCharacteristic Equation:') 
print('det(A - lambda*I) = 0')

# e) Eigenvalues
values, vectors = np.linalg.eig(A)
print('\nEigenvalues of A:')
print(values)

# f) Interpretation
print('\nInterpretation of Eigenvalues:')
print('The eigenvalues represent scaling factors that leave the transformed vector in the column space of A.')

# g) Positive definiteness 
print('\nA is positive definite?')
print(np.all(values > 0))

Matrix Equation:
A * x = b

Determinant of A:
-12.0

Inverse of A:
[[ 0.41666667 -0.5        -0.16666667]
 [ 0.08333333  0.5         0.16666667]
 [-0.91666667  1.5         0.16666667]]

Characteristic Equation:
det(A - lambda*I) = 0

Eigenvalues of A:
[-4.  3.  1.]

Interpretation of Eigenvalues:
The eigenvalues represent scaling factors that leave the transformed vector in the column space of A.

A is positive definite?
False
